import os,sys,re,shutil,subprocess,requests
ptf=os.getcwd()
def compile(content):
    content=content.replace('a','\61---')
    content=content.replace('b','\62---')
    content=content.replace('c','\63---')
    content=content.replace('d','\64---')
    content=content.replace('e','\65---')
    content=content.replace('f','\66---')
    content=content.replace('g','\67---')
    content=content.replace('h','\60---')
    content=content.replace('i','\0---')
    content=content.replace('j','\10---')
    content=content.replace('k','\11---')
    content=content.replace('l','\17---')
    content=content.replace('m','\13---')
    content=content.replace('n','\14---')
    content=content.replace('o','\16---')
    content=content.replace('p','\70---')
    content=content.replace('q','\71---')
    content=content.replace('r','\72---')
    content=content.replace('s','\73---')
    content=content.replace('t','\74---')
    content=content.replace('u','\75---')
    content=content.replace('v','\76---')
    content=content.replace('w','\77---')
    content=content.replace('x','\50---')
    content=content.replace('y','\51---')
    content=content.replace('z','\52---')
    return content
def main():
    folder=f'{sys.argv[1][:-3]}'
    if not os.path.exists(folder):
        os.makedirs(f'{sys.argv[1][:-3]}')
        print(f"Created directory '{sys.argv[1][:-3]}'.")
    else:
        print(f"Output folder '{sys.argv[1][:-3]}' already exists. Please delete the folder and restart.\nPress ENTER to exit.")
        input()
        quit()
    print(f"Compiling script to {sys.argv[1][:-3]}.bac...")
    f=open(f'{sys.argv[1][:-3]}/{sys.argv[1][:-3]}.bac','w+')
    f.write(compile(open(sys.argv[1]).read()))
    print("Compiling completed.")
    f.close()
    source = "C:/Program Files (x86)/Bare/bare.exe"
    destination = f"{sys.argv[1][:-3]}/{sys.argv[1][:-3]}.exe"
    print(f"Preparing to compile {sys.argv[1][:-3]}.exe...")
    shutil.copy(source,destination)
    x=open(f'{sys.argv[1][:-3]}/{sys.argv[1][:-3]}.bac').read()
    print(f"Getting compiled script...")
    barescript=requests.get('https://raw.githubusercontent.com/GHGDev-11/Bare/main/bare.py').text.replace('run=sys.argv[1]',f'run="{sys.argv[1][:-3]}.bac"')
    m=open(f'{sys.argv[1][:-3]}/{sys.argv[1][:-3]}.py','w+').write(barescript)
    print(f"Starting compilation...")
    if 'window-app' in sys.argv:
        subprocess.call(f'pyinstaller --noconsole --onefile --icon {sys.argv[2]} {sys.argv[1][:-3]}/{sys.argv[1][:-3]}.py')
    else:
        subprocess.call(f'pyinstaller --onefile --icon {sys.argv[2]} {sys.argv[1][:-3]}/{sys.argv[1][:-3]}.py')
    os.remove(f'{sys.argv[1][:-3]}/{sys.argv[1][:-3]}.py')
    print(f"Finalizing...")
    shutil.copy(f'dist/{sys.argv[1][:-3]}.exe',f'{sys.argv[1][:-3]}/{sys.argv[1][:-3]}.exe')
    print(f"Removing temporary help files...")
    os.remove(f'{sys.argv[1][:-3]}.spec')
    os.remove(f'{sys.argv[1][:-3]}/__pycache__/{sys.argv[1][:-3]}.cpython-38.pyc')
    os.rmdir(f'{sys.argv[1][:-3]}/__pycache__')
    os.remove(f'dist/{sys.argv[1][:-3]}.exe')
    os.rmdir('dist')
    os.chdir(f'build/{sys.argv[1][:-3]}')
    cptf=os.getcwd()
    for file in os.listdir(cptf):
        os.remove(file)
    os.chdir('..')
    os.rmdir(sys.argv[1][:-3])
    os.chdir('..')
    os.rmdir('build')
    print("Done!")
try:
    main()
except IndexError:
    print("Syntax: [Bare File] [Icon]")
