import re
def compile(content):
    content=content.replace('a','\61---')
    content=content.replace('b','\62---')
    content=content.replace('c','\63---')
    content=content.replace('d','\64---')
    content=content.replace('e','\65---')
    content=content.replace('f','\66---')
    content=content.replace('g','\67---')
    content=content.replace('h','\60---')
    content=content.replace('i','\0---')
    content=content.replace('j','\10---')
    content=content.replace('k','\11---')
    content=content.replace('l','\17---')
    content=content.replace('m','\13---')
    content=content.replace('n','\14---')
    content=content.replace('o','\16---')
    content=content.replace('p','\70---')
    content=content.replace('q','\71---')
    content=content.replace('r','\72---')
    content=content.replace('s','\73---')
    content=content.replace('t','\74---')
    content=content.replace('u','\75---')
    content=content.replace('v','\76---')
    content=content.replace('w','\77---')
    content=content.replace('x','\50---')
    content=content.replace('y','\51---')
    content=content.replace('z','\52---')
    return content
import sys
if __name__ == "__main__":
    c=compile(open(sys.argv[1]).read())
    a=sys.argv[1].split('.')
    for i in a:
        if i=='ba':
            a.remove(i)
    u=str(a).replace('[','').replace(']','').replace("'",'')
    f=open(f'{u}.bac','w+')
    f.write(c)
    f.close()
